# Day
# Goog
# wqer qwer qwe rqw er
one: # comweqg
  two: # comments
    three: "Gau" # comments23
    four: 12 # commentdwe
    dict: # fgwer wergwerg
      # werfwerfwerg
      - key: "value" # gwegwerg
        key2: "value"
      - four: "five"
        subdict:
          - key: "value"
            key2: "value"
          - four: "five"